/**
 * Flowtype definitions for dialog
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.10.0
 * @flow
 */

declare module 'N/ui/dialog' {

  declare interface AlertOptions {
    title?: string;
    message?: string;
  }
  declare interface CreateDialogOptions {
    buttons?: DialogButton[];
    title?: string;
    message?: string;
  }
  declare interface DialogButton {
    label: string;
    value: number | string;
  }

  declare export interface NUi$Dialog {
    alert(options: AlertOptions): Promise<boolean>;
    confirm(options: AlertOptions): Promise<boolean>;
    create(options: CreateDialogOptions): Promise<string>;
  }

}
