/**
 * Flowtype definitions for message
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.10.0
 * @flow
 */

declare module 'N/ui/message' {

  declare interface Message {
    hide(): void;
    show(options?: MessageShowOptions): void;
  }
  declare export interface MessageCreateOptions {
    message?: string;
    title?: string;
    type: $Values<typeof Type>;

    /**
     * The amount of time, in milliseconds, to show the message. The default is 0, which shows the message until Message.hide() is called.
     * If you specify a duration for message.create() and message.show(), the value from the message.show() method call takes precedence.
     */
    duration?: number;
  }
  declare interface MessageShowOptions {
    duration?: number;
  }
  declare type TypeT ={|
                       +CONFIRMATION: 0, // 0
                       +INFORMATION: 1, // 1
                       +WARNING: 2, // 2
                       +ERROR: 3 // 3
                       |};

  declare export interface NUi$Message {
    create(options: MessageCreateOptions): Message;
    Type: TypeT;
  }

}
