/**
 * Flowtype definitions for recordView
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.10.0
 * @flow
 */

/**
 * Load the N/commerce/recordView module when you want to provide fast, cached, and public access to the item fields and website settings.
 */
declare module 'N/commerce/recordView' {

  declare interface RecordViewOptions {
    /**
     * IDs of the item you want to view
     */
    ids: number[];

    /**
     * Item fields you want to retrieve for the items
     */
    +fields: string | string[];

    /**
     * Options that affect related fields. Array of name, value pairs. Type depends upon parameter.
     * Supported field options (viewItems only):
     * - includeVat: this affects onlinecustomerprice_detail field. Default value is false.
     */
    fieldOptions?: {
      +[fieldId: string]: string | boolean,
      ...
    }[];
  }

  declare export interface NCommerce$RecordView {
    /**
     * Retrieves one or more Items with requested items fields from an Item Record.
     */
    viewItems(options: RecordViewOptions): {
      [fieldId: string]: string | number | boolean,
      ...
    };

    /**
     * Retrieves the website details with requested website fields.
     */
    viewWebsite(options: RecordViewOptions): {
      [fieldId: string]: string | number | boolean,
      ...
    };
  }

}
