/**
 * Flowtype definitions for currency
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.10.0
 * @flow
 */

declare module 'N/currency' {

  declare interface ExchangeRateOptions {
    /**
     * The point in time to evaluate currency.
     */
    date?: Date;

    /**
     * The internal ID or three-letter ISO code for the currency you are converting from.
     */
    +source: number | string;

    /**
     * The internal ID or three-letter ISO code for the currency you are converting to.
     */
    +target: number | string;
  }

  declare export interface NCurrency {
    /**
     * Method used to return the exchange rate between two currencies based on a certain date.
     * The exchange rate values are sourced from the Currency Exchange Rate record.
     */
    exchangeRate(options: ExchangeRateOptions): number;
  }

}
