/**
 * Flowtype definitions for error
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.10.0
 * @flow
 */

declare module 'N/error' {

  declare interface EventType {
    beforeLoad: string;
    beforeSubmit: string;
    afterSubmit: string;
  }
  declare interface CreateOptions {
    /**
     * A user-defined name (error code).
     */
    name: string;

    /**
     * The error message displayed. This value displays on the Execution Log, in the Details column.
     */
    +message: string | Error | SuiteScriptError | UserEventError;

    /**
     * Sets whether email notification is suppressed. The default value is false.
     */
    notifyOff?: boolean;
  }
  /**
   * Encapsulates a SuiteScript error thrown by any script type that is not a user event script.
   */
  declare export interface SuiteScriptError {
    /**
     * Error ID that is automatically generated when a new error is created.
     */
    id: $ReadOnly<string>;

    /**
     * Text that displays on the SuiteScript Execution Log, in the Details column.
     */
    message: $ReadOnly<string>;

    /**
     * A user-defined name (error code).
     */
    name: $ReadOnly<string>;

    /**
     * A list of method calls that the script is executing when the error is thrown. The most recently executed method is listed at the top.
     */
    stack: $ReadOnly<string[]>;

    /**
     * The cause of the error message.
     */
    cause: $ReadOnly<any>;

    /**
     * Whether email notification is suppressed.
     */
    notifyOff?: boolean;
  }
  /**
   * Encapsulates a SuiteScript error thrown by a user event script.
   */
  declare export interface UserEventError {
    /**
     * The user event type. Holds one of the following values: beforeLoad, beforeSubmit, afterSubmit.
     */
    eventType: $ReadOnly<EventType>;

    /**
     * Error ID that is automatically generated when a new error is created.
     */
    id: $ReadOnly<string>;

    /**
     * Text that displays on the SuiteScript Execution Log, in the Details column.
     */
    message: $ReadOnly<string>;

    /**
     * A user-defined name (error code).
     */
    name: $ReadOnly<string>;

    /**
     * The internal ID of the submitted record that triggered the script. This property only holds a value when the error is thrown by an afterSubmit user event script.
     */
    recordId: $ReadOnly<string>;

    /**
     * A list of method calls that the script is executing when the error is thrown. The most recently executed method is listed at the top.
     */
    stack: $ReadOnly<string[]>;
  }

  declare export interface NError {
    /**
     * Creates a new error.SuiteScriptError or error.UserEventError object.
     */
    create<T: SuiteScriptError | UserEventError>(options: CreateOptions): T;
  }

}
