/**
 * Flowtype definitions for record
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.10.0
 * @flow
 */

declare module 'N/record' {

  import type { AddSelectOptionOptions } from "N/ui/serverWidget";

  /**
   * Submits a new record or saves edits to an existing record.
   * @governance 20 units for transactions, 4 for custom records, 10 for all other records
   * @return id of submitted record
   */
  declare interface RecordSaveFunction {
    (options?: SubmitConfig): number;
    promise(options?: SubmitConfig): Promise<number>;
  }
  declare interface AttachOptions {
    /**
     * The record to attach.
     */
    record: AttachRecordOptions;

    /**
     * The record that the options.record gets attached to.
     */
    to: AttachRecordOptions;

    /**
     * The name-value pairs containing attributes for the attachment.
     */
    attributes?: any;
  }
  declare interface AttachRecordOptions {
    /**
     * The type of record to attach.
     */
    +type: $Values<TypeT> | string;

    /**
     * The internal ID of the record to attach.
     */
    +id: number | string;
  }
  declare interface CancelCommitLineOptions {
    /**
     * The internal ID of the sublist.
     */
    sublistId: string;
  }
  declare interface CopyLoadOptions {
    /**
     * The record type.
     */
    +type: $Values<TypeT> | string;

    /**
     * The internal ID of the existing record instance in NetSuite.
     */
    +id: FieldValue | number | string;

    /**
     * Determines whether the new record is dynamic. If set to true, the record is created in dynamic mode. If set to false, the record is created in standard mode. By default, this value is false.
     * - When a SuiteScript 2.0 script creates, copies, loads, or transforms a record in standard mode, the record’s body fields and sublist line items are not sourced, calculated, and validated until the record is saved (submitted) with Record.save(options).
     * - When you work with a record in standard mode, you do not need to set values in any particular order. After submitting the record, NetSuite processes the record’s body fields and sublist line items in the correct order, regardless of the organization of your script.
     * - When a SuiteScript 2.0 script creates, copies, loads, or transforms a record in dynamic mode, the record’s body fields and sublist line items are sourced, calculated, and validated in real-time. A record in dynamic mode emulates the behavior of a record in the UI.
     * - When you work with a record in dynamic mode, it is important that you set values in the same order you would within the UI. If you fail to do this, your results may not be accurate.
     */
    isDynamic?: boolean;

    /**
     * Name-value pairs containing default values of fields in the new record.
     */
    defaultValue?: {
      [fieldId: string]: any,
      ...
    };
  }
  declare interface DetachOptions {
    /**
     * The record to be detached.
     */
    record: AttachRecordOptions;

    /**
     * The destination record that options.record should be detached from.
     */
    from: AttachRecordOptions;

    /**
     * Name-value pairs containing default values of fields in the new record.
     */
    attributes?: any;
  }
  declare interface FindSublistLineWithValueOptions {
    /**
     * The internal ID of the sublist.
     */
    sublistId: string;

    /**
     * The internal ID of a standard or custom sublist field.
     */
    fieldId: string;

    /**
     * The value to search for.
     */
    value: FieldValue;
  }
  declare interface GetCurrentSublistValueOptions {
    /**
     * The internal ID of the sublist.
     */
    sublistId: string;

    /**
     * The internal ID of a standard or custom sublist field.
     */
    fieldId: string;
  }
  declare interface GetFieldOptions {
    /**
     * The internal ID of a standard or custom body field.
     */
    fieldId: string;
  }
  declare interface RecordGetLineCountOptions {
    /**
     * The internal ID of the sublist.
     */
    sublistId: string;
  }
  declare interface GetMatrixHeaderCountOptions {
    /**
     * The internal ID of the sublist that contains the matrix.
     */
    sublistId: string;

    /**
     * The internal ID of the matrix field.
     */
    fieldId: string;
  }
  declare interface GetMatrixHeaderFieldOptions {
    /**
     * The internal ID of the sublist that contains the matrix.
     */
    sublistId: string;

    /**
     * The internal ID of the matrix field.
     */
    fieldId: string;

    /**
     * The column number for the field.
     */
    column: number;
  }
  declare interface GetMatrixSublistFieldOptions {
    /**
     * The internal ID of the sublist that contains the matrix.
     */
    sublistId: string;

    /**
     * The internal ID of the matrix field.
     */
    fieldId: string;

    /**
     * The line number for the field.
     */
    line: number;
  }
  declare interface GetMatrixSublistValueOptions {
    /**
     * The internal ID of the sublist that contains the matrix.
     */
    sublistId: string;

    /**
     * The internal ID of the matrix field.
     */
    fieldId: string;

    /**
     * The line number for the field.
     */
    line: number;

    /**
     * the column number for the field
     */
    column: number;
  }
  declare interface GetSublistValueOptions {
    /**
     * The internal ID of the sublist.
     */
    sublistId: string;

    /**
     * The internal ID of a standard or custom sublist field.
     */
    fieldId: string;

    /**
     * The line number for the field.
     */
    line: number;
  }
  declare interface GetCurrentSublistFieldOptions {
    /**
     * The internal ID of the sublist.
     */
    sublistId: string;

    /**
     * The internal ID of a standard or custom sublist field.
     */
    fieldId: string;
  }
  declare interface GetSublistFieldOptions {
    /**
     * The internal ID of the sublist.
     */
    sublistId: string;

    /**
     * The internal ID of a standard or custom sublist field.
     */
    fieldId: string;

    /**
     * The line number for the field.
     */
    line: number;
  }
  declare interface HasSubrecordOptions {
    /**
     * The internal ID of the field that may contain a subrecord.
     */
    fieldId: string;
  }
  declare interface InsertLineOptions {
    /**
     * The internal ID of the sublist.
     */
    sublistId: string;

    /**
     * The line number to insert.
     */
    line: number;

    /**
     * If set to true, scripting recalculation is ignored. Default is false.
     */
    ignoreRecalc?: boolean;
  }
  declare interface SelectLineOptions {
    /**
     * The internal ID of the sublist.
     */
    sublistId: string;

    /**
     * The line number to select in the sublist.
     */
    line: number;
  }
  declare interface SetCurrentMatrixSublistValueOptions {
    /**
     * The internal ID of the sublist.
     */
    sublistId: string;

    /**
     * The internal ID of a standard or custom sublist field.
     */
    fieldId: string;

    /**
     * The column number for the field.
     */
    column: number;

    /**
     * The value to set the field to.
     * The value type must correspond to the field type being set. For example:
     * - Text, Radio and Select fields accept string values.
     * - Checkbox fields accept Boolean values.
     * - Date and DateTime fields accept Date values.
     * - Integer, Float, Currency and Percent fields accept number values.
     */
    +value: FieldValue;

    /**
     * If set to true, the field change and slaving event is ignored. Default is false.
     */
    ignoreFieldChange?: boolean;

    /**
     * Indicates whether to perform slaving synchronously.
     */
    fireSlavingSync?: boolean;

    /**
     * Use forceSyncSourcing instead of fireSlavingSync on currentRecord module.
     */
    forceSyncSourcing?: boolean;
  }
  declare interface SetCurrentSublistValueOptions {
    /**
     * The internal ID of the sublist.
     */
    sublistId: string;

    /**
     * The internal ID of a standard or custom sublist field.
     */
    fieldId: string;

    /**
     * The value to set the field to.
     * The value type must correspond to the field type being set. For example:
     * - Text, Radio and Select fields accept string values.
     * - Checkbox fields accept Boolean values.
     * - Date and DateTime fields accept Date values.
     * - Integer, Float, Currency and Percent fields accept number values.
     */
    +value: FieldValue;

    /**
     * If set to true, the field change and slaving event is ignored. Default is false.
     */
    ignoreFieldChange?: boolean;

    /**
     * Documented in N/currentRecord but not N/record. Set to true to synchronously set this value and its sourced values before returning.
     */
    fireSlavingSync?: boolean;

    /**
     * Use forceSyncSourcing instead of fireSlavingSync on currentRecord module.
     */
    forceSyncSourcing?: boolean;
  }
  declare interface SetCurrentSublistTextOptions {
    /**
     * The internal ID of the sublist.
     */
    sublistId: string;

    /**
     * The internal ID of a standard or custom sublist field.
     */
    fieldId: string;

    /**
     * The text to set the value to.
     */
    +text: string | string[];

    /**
     * If set to true, the field change and slaving event is ignored. Default is false.
     */
    ignoreFieldChange?: boolean;

    /**
     * Indicates whether to perform field sourcing synchronously.
     * If set to true, sources dependent field information for empty fields synchronously.
     * Defaults to false – dependent field values are not sourced synchronously.
     */
    fireSlavingSync?: boolean;

    /**
     * Use forceSyncSourcing instead of fireSlavingSync on currentRecord module.
     */
    forceSyncSourcing?: boolean;
  }
  declare interface SetValueOptions {
    /**
     * The internal ID of a standard or custom body field.
     */
    fieldId: string;

    /**
     * The value to set the field to.
     * The value type must correspond to the field type being set. For example:
     * - Text, Radio and Select fields accept string values.
     * - Checkbox fields accept Boolean values.
     * - Date and DateTime fields accept Date values.
     * - Integer, Float, Currency and Percent fields accept number values.
     */
    +value: FieldValue;

    /**
     * If set to true, the field change and slaving event is ignored.
     */
    ignoreFieldChange?: boolean;

    /**
     * Documented in N/currentRecord but not N/record. Set to true to synchronously set this value and its sourced values before returning.
     */
    fireSlavingSync?: boolean;

    /**
     * Use forceSyncSourcing instead of fireSlavingSync on currentRecord module.
     */
    forceSyncSourcing?: boolean;
  }
  declare interface SetFieldTextOptions {
    /**
     * The internal ID of a standard or custom body field.
     */
    fieldId: string;

    /**
     * The text to change the field value to.
     */
    +text: string | string[];

    /**
     * If set to true, the field change and slaving event is ignored. Default is false.
     */
    ignoreFieldChange?: boolean;

    /**
     * Documented in N/currentRecord but not N/record. Set to true to synchronously set this value and its sourced values before returning.
     */
    fireSlavingSync?: boolean;

    /**
     * Use forceSyncSourcing instead of fireSlavingSync on currentRecord module.
     */
    forceSyncSourcing?: boolean;
  }
  declare interface SetSublistTextOptions {
    /**
     * The internal ID of the sublist.
     */
    sublistId: string;

    /**
     * The internal ID of a standard or custom sublist field.
     */
    fieldId: string;

    /**
     * The line number for the field.
     */
    line: number;

    /**
     * The text to set the value to.
     */
    text: string;

    /**
     * WARNING - UNDOCUMENTED. Set to true to synchronously set this value and its sourced values before returning.
     */
    fireSlavingSync?: boolean;

    /**
     * Use forceSyncSourcing instead of fireSlavingSync on currentRecord module.
     */
    forceSyncSourcing?: boolean;
  }
  declare interface SetSublistValueOptions {
    /**
     * The internal ID of the sublist.
     */
    sublistId: string;

    /**
     * The internal ID of a standard or custom sublist field.
     */
    fieldId: string;

    /**
     * The internal ID of a standard or custom sublist field.
     */
    line: number;

    /**
     * The value to set the sublist field to.
     * The value type must correspond to the field type being set. For example:
     * - Text, Radio and Select fields accept string values.
     * - Checkbox fields accept Boolean values.
     * - Date and DateTime fields accept Date values.
     * - Integer, Float, Currency and Percent fields accept number values.
     */
    +value: FieldValue;

    /**
     * WARNING - UNDOCUMENTED. Set to true to synchronously set this value and its sourced values before returning.
     */
    fireSlavingSync?: boolean;

    /**
     * Use forceSyncSourcing instead of fireSlavingSync on currentRecord module.
     */
    forceSyncSourcing?: boolean;
  }
  declare interface GetSelectOptionsOpts {
    /**
     * The search string to filter the select options that are returned.
     */
    filter: string;

    /**
     * The following operators are supported: contains, is, startswith. Default is contains.
     */
    +operator: "contains" | "is" | "startswith";
  }
  declare export interface Sublist {
    /**
     * The name of the sublist.
     */
    name: string;

    /**
     * The name of the sublist.
     */
    id: string;

    /**
     * The type of the sublist.
     */
    type: string;

    /**
     * The sublist is changed
     */
    isChanged: boolean;

    /**
     * The sublist is hidden
     */
    isHidden: boolean;

    /**
     * The sublist is display
     */
    isDisplay: boolean;

    /**
     * A flag to indicate whether or not the sublist supports multi-line buffer feature.
     */
    isMultilineEditable: boolean;

    /**
     * Returns a column in the sublist.
     * Client and server-side scripts
     */
    getColumn(options: GetColumnOptions): Column;

    /**
     * Returns the object type name (sublist.Sublist)
     */
    toString(): string;

    /**
     * JSON.stringify() implementation.
     */
    toJSON(): {
      id: string,
      type: string,
      isChanged: boolean,
      isDisplay: boolean,
      ...
    };
  }
  declare export interface GetColumnOptions {
    /**
     * The internal ID of the column field in the sublist.
     */
    fieldId: string;
  }
  /**
   * Encapsulates a column of a sublist on a standard or custom record.
   * For a complete list of this object’s properties, see Column Object Members.
   * This object does not return a value, it returns information about the sublist column.
   * Client and server-side scripts
   */
  declare export interface Column {
    /**
     * Client and server-side scripts. Returns the internal ID of the column.
     */
    id: string;

    /**
     * Client and server-side scripts. Returns the column type.
     */
    type: string;

    /**
     * Client and server-side scripts. Returns the UI label for the column.
     */
    label: string;

    /**
     * Client and server-side scripts. Returns the internal ID of the standard or custom sublist that contains the column.
     */
    sublistId: string;
  }
  /**
   * Client and server-side scripts.
   * Encapsulates a body or sublist field on a standard or custom record.
   */
  declare export interface Field {
    /**
     * Adds the select options that appears in the dropdown of a field.
     */
    insertSelectOption(options: AddSelectOptionOptions): void;

    /**
     * Returns an array of available options on a standard or custom select, multi-select, or radio field as key-value pairs. Only the first 1,000 available options are returned.
     *
     * Returns only the first 1,000 available options are returned in an array. If there are more than 1,000 available options, an empty array [] is returned. This function returns an array in the following format: `[{value: 5, text: 'abc'},{value: 6, text: '123'}]`.
     *
     * This function returns Type Error if the field is not a supported field for this method.
     */
    getSelectOptions(
      options?: GetSelectOptionsOpts
    ): {
      value: any,
      text: string,
      ...
    }[];

    /**
     * Removes a single select option from a select or multiselect field added via script.
     * Note that this API call can only be used on select/multiselect fields that are added via the UI Objects API (for example on Suitelets or beforeLoad user event scripts).
     */
    removeSelectOption(options?: {
      value: string,
      ...
    }): void;

    /**
     * get JSON format of the object
     */
    toJSON(
      options?: any
    ): {
      id: string,
      label: string,
      type: string,
      ...
    };
    toString(options?: any): string;

    /**
     * Returns the UI label for a standard or custom field body or sublist field.
     */
    label: string;

    /**
     * Returns the internal ID of a standard or custom body or sublist field.
     */
    id: string;

    /**
     * Returns the type of a body or sublist field.
     */
    type: string;

    /**
     * Returns true if the standard or custom field is mandatory on the record form, or false otherwise.
     */
    isMandatory: boolean;

    /**
     * Returns true if the standard or custom field is disabled on the record form, or false otherwise.
     */
    isDisabled: boolean;

    /**
     * Returns true if the field is a popup list field, or false otherwise.
     */
    isPopup: boolean;

    /**
     * Returns true if the field is set to display on the record form, or false otherwise.
     */
    isDisplay: boolean;

    /**
     * Returns true if the field is visible on the record form, or false otherwise.
     */
    isVisible: boolean;

    /**
     * Returns true if the field on the record form cannot be edited, or false otherwise.
     * For textarea fields, this property can be read or written to. For all other fields, this property is read-only.
     */
    isReadOnly: boolean;

    /**
     * Return the sublistId of the field
     */
    sublistId: string;
  }
  declare export type FieldValue =
    | Date
    | number
    | string
    | boolean
    | Array<number | string>
    | null;
  /**
   * Almost like a full Record, except without things like save().
   */
  declare export class ClientCurrentRecord {
    /**
     * Cancels the currently selected line on a sublist.
     */
    cancelLine(options: CancelCommitLineOptions): Record;
    cancelLine(sublistId: string): Record;

    /**
     * Commits the currently selected line on a sublist.
     */
    commitLine(options: CancelCommitLineOptions): Record;
    copy: RecordCopyFunction;

    /**
     * Performs macro operation and returns its result in a plain JavaScript object.
     */
    executeMacro: ExecuteMacroFunction;

    /**
     * Returns the line number of the first instance where a specified value is found in a specified column of the matrix.
     */
    findMatrixSublistLineWIthValue(
      options: FindSublistLineWithValueOptions
    ): number;

    /**
     * Returns the line number for the first occurrence of a field value in a sublist.
     */
    findSublistLineWithValue(options: FindSublistLineWithValueOptions): number;

    /**
     * Gets the value for the currently selected line in the matrix.
     */
    getCurrentMatrixSublistValue(
      options: GetCurrentSublistValueOptions
    ): number | Date | string | string[] | boolean;

    /**
     * Returns the line number of the currently selected line.
     */
    /**
     * return field object from record's sublist current line. Only available in dynamic record
     * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT if sublistId or fieldId is missing
     * @restriction only available in dynamic record
     */
    getCurrentSublistField(options: GetCurrentSublistFieldOptions): Field;
    getCurrentSublistIndex(options: RecordGetLineCountOptions): number;

    /**
     * Gets the subrecord for the associated sublist field on the current line.
     */
    getCurrentSublistSubrecord(options: GetCurrentSublistValueOptions): Record;

    /**
     * Returns a text representation of the field value in the currently selected line.
     */
    getCurrentSublistText(options: GetCurrentSublistValueOptions): string;

    /**
     * Returns the value of a sublist field on the currently selected sublist line.
     */
    getCurrentSublistValue(options: GetCurrentSublistValueOptions): FieldValue;
    getCurrentSublistValue(sublistId: string, fieldId: string): FieldValue;

    /**
     * Returns a field object from a record.
     * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT if options.fieldId is missing or undefined
     */
    getField(options: GetFieldOptions): Field;

    /**
     * Returns the number of lines in a sublist.
     */
    getLineCount(options: RecordGetLineCountOptions): number;
    getLineCount(sublistId: string): number;

    /**
     * Provides a macro to be executed.
     */
    getMacro(options: {
      id: string,
      ...
    }): Function;

    /**
     * Provides a plain JavaScript object of available macro objects defined for a record type, indexed by the Macro ID.
     */
    getMacros(): {
      [macroId: string]: Macro,
      ...
    };

    /**
     * Returns the number of columns for the specified matrix.
     */
    getMatrixHeaderCount(options: GetMatrixHeaderCountOptions): number;

    /**
     * Gets the field for the specified header in the matrix.
     * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT if any required values are missing
     */
    getMatrixHeaderField(options: GetMatrixHeaderFieldOptions): Field;

    /**
     * Gets the value for the associated header in the matrix.
     */
    getMatrixHeaderValue(options: GetMatrixHeaderFieldOptions): FieldValue;

    /**
     * Gets the field for the specified sublist in the matrix.
     */
    getMatrixSublistField(options: GetMatrixSublistFieldOptions): Field;

    /**
     * Gets the value for the associated field in the matrix.
     */
    getMatrixSublistValue(options: GetMatrixSublistValueOptions): FieldValue;

    /**
     * Returns the specified sublist.
     */
    getSublist(options: RecordGetLineCountOptions): Sublist;

    /**
     * Return field object from record's sublist
     * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT if sublistId or fieldId is missing
     * @throws {SuiteScriptError} SSS_INVALID_SUBLIST_OPERATION if line number is invalid
     */
    getSublistField(options: GetSublistFieldOptions): Field;

    /**
     * Returns the value of a sublist field in a text representation.
     */
    getSublistText(options: GetSublistValueOptions): string;

    /**
     * Returns the value of a sublist field.
     */
    getSublistValue(options: GetSublistValueOptions): FieldValue;
    getSublistValue(sublistId: string, fieldId: string, line: number): FieldValue;

    /**
     * Gets the subrecord for the associated field.
     */
    getSubrecord(options: GetFieldOptions): Record;

    /**
     * Returns the text representation of a field value.
     */
    getText(options: GetFieldOptions): string | string[];
    getText(fieldId: string): string | string[];

    /**
     * Returns the value of a field.
     */
    getValue(options: GetFieldOptions): FieldValue;
    getValue(fieldId: string): FieldValue;

    /**
     * Returns a value indicating whether the associated sublist field has a subrecord on the current line. This method can only be used on dynamic records.
     */
    hasCurrentSublistSubrecord(options: GetCurrentSublistValueOptions): boolean;

    /**
     * Returns a value indicating whether the associated sublist field contains a subrecord.
     */
    hasSublistSubrecord(options: GetSublistValueOptions): boolean;

    /**
     * Returns a value indicating whether the field contains a subrecord.
     */
    hasSubrecord(options: HasSubrecordOptions): boolean;

    /**
     * The internal ID of a specific record.
     */
    id: number;

    /**
     * Inserts a sublist line.
     */
    insertLine(options: InsertLineOptions): void;

    /**
     * Indicates whether the record is in dynamic or standard mode.
     * - If set to true, the record is currently in dynamic mode. If set to false, the record is currently in standard mode.
     *   - When a SuiteScript 2.0 script creates, copies, loads, or transforms a record in standard mode, the record’s body fields and sublist line items are not sourced, calculated, and validated until the record is saved (submitted) with Record.save(options).
     *   - When you work with a record in standard mode, you do not need to set values in any particular order. After submitting the record, NetSuite processes the record’s body fields and sublist line items in the correct order, regardless of the organization of your script.
     *   - When a SuiteScript 2.0 script creates, copies, loads, or transforms a record in dynamic mode, the record’s body fields and sublist line items are sourced, calculated, and validated in real-time. A record in dynamic mode emulates the behavior of a record in the UI.
     *   - When you work with a record in dynamic mode, it is important that you set values in the same order you would within the UI. If you fail to do this, your results may not be accurate.
     * This value is set when the record is created or accessed.
     */
    isDynamic: boolean;

    /**
     * Removes the subrecord for the associated sublist field on the current line.
     * @return {Record} same record, for chaining
     */
    removeCurrentSublistSubrecord(options: GetCurrentSublistValueOptions): this;

    /**
     * Removes a sublist line.
     * @return {Record} same record, for chaining
     */
    removeLine(options: InsertLineOptions): this;

    /**
     * Removes the subrecord for the associated field.
     * @return {Record} same record, for chaining
     */
    removeSubrecord(options: RecordGetLineCountOptions): this;

    /**
     * Selects an existing line in a sublist.
     */
    selectLine(options: SelectLineOptions): void;
    selectLine(sublistId: string, line: number): void;

    /**
     * Selects a new line at the end of a sublist.
     */
    selectNewLine(options: RecordGetLineCountOptions): void;

    /**
     * Sets the value for the line currently selected in the matrix.
     */
    setCurrentMatrixSublistValue(
      options: SetCurrentMatrixSublistValueOptions
    ): Record;

    /**
     * Sets the value for the field in the currently selected line by a text representation.
     */
    setCurrentSublistText(options: SetCurrentSublistTextOptions): void;

    /**
     * Sets the value for the field in the currently selected line.
     */
    setCurrentSublistValue(options: SetCurrentSublistValueOptions): void;
    setCurrentSublistValue(
      sublistId: string,
      fieldId: string,
      value: FieldValue
    ): void;

    /**
     * Sets the value for the associated header in the matrix.
     */
    setMatrixHeaderValue(options: SetCurrentMatrixSublistValueOptions): Record;

    /**
     * Sets the value for the associated field in the matrix.
     */
    setMatrixSublistValue(options: SetSublistValueOptions): Record;

    /**
     * Sets the value of the field by a text representation.
     */
    setText(options: SetFieldTextOptions): void;
    setText(fieldId: string, value: string): void;

    /**
     * Sets the value of a field.
     */
    setValue(options: SetValueOptions): void;
    setValue(fieldId: string, value: FieldValue): void;

    /**
     * The record type.
     */
    type: $Values<TypeT> | string;
  }
  declare export class Record extends ClientCurrentRecord {
    /**
     * Returns the body field names (internal ids) of all the fields in the record, including machine header field and matrix header fields.
     */
    getFields(): string[];

    /**
     * Returns all the names of all the sublists.
     */
    getSublists(): string[];

    /**
     * Returns all the field names in a sublist.
     */
    getSublistFields(options: RecordGetLineCountOptions): string[];

    /**
     * Gets the subrecord associated with a sublist field.
     */
    getSublistSubrecord(options: GetSublistValueOptions): Record;

    /**
     * Removes the subrecord for the associated sublist field.
     * @restriction only available in deferred dynamic record
     * @return {Record} same record, for chaining
     */
    removeSublistSubrecord(options: GetSublistValueOptions): this;

    /**
     * Submits a new record or saves edits to an existing record.
     * @governance 20 units for transactions, 4 for custom records, 10 for all other records
     * @return id of submitted record
     */
    save: RecordSaveFunction;

    /**
     * Sets the value of a sublist field by a text representation.
     */
    setSublistText(options: SetSublistTextOptions): Record;

    /**
     * Sets the value of a sublist field. (standard mode only).
     */
    setSublistValue(options: SetSublistValueOptions): Record;
    toString(): string;

    /**
     * get JSON format of the object, something like `{id: string, type: string, fields: {[fieldId: string]: any}, sublists: {[sublistId:string]: {[line_id:string]:{[sublist_field_id:string]: string}}}`
     */
    toJSON(): RecordToJSONReturnValue;
  }
  declare export type RecordToJSONReturnValue = {
    id: string,
    type: string,
    isDynamic: boolean,
    fields: {
      [fieldId: string]: string,
      ...
    },
    sublists: {
      [sublistId: string]: {
        [lineDescription: string]: string,
        ...
      },
      ...
    },
    ...
  };
  declare interface ExecuteMacroFunction {
    (options: {
      id: string,
      params: Object,
      ...
    }): Object;
    promise(options: {
      id: string,
      params: Object,
      ...
    }): Object;
  }
  declare interface MacroExecuteFunction {
    (options?: {
      params?: Object,
      ...
    }): {
      notifications: any[],
      response: Object,
      ...
    };
    promise(options?: {
      params?: Object,
      ...
    }): Promise<{
      notifications: any[],
      response: Object,
      ...
    }>;
  }
  declare interface Macro {
    execute: MacroExecuteFunction;
    id: string;
    label: string;
    description: string;
    attributes: Object;
  }
  declare interface SubmitConfig {
    /**
     * Indicates whether to enable sourcing during the record update. Defaults to true.
     */
    enableSourcing?: boolean;

    /**
     * Indicates whether to ignore mandatory fields during record submission. Default is false.
     */
    ignoreMandatoryFields?: boolean;
  }
  declare export interface SubmitFieldsOptions {
    /**
     * The type of record.
     */
    +type: $Values<TypeT> | string;

    /**
     * The internal ID of the existing record instance in NetSuite.
     */
    +id: string | number;

    /**
     * The ID-value pairs for each field you want to edit and submit.
     */
    values: any;

    /**
     * Additional options to set for the record.
     */
    options?: SubmitConfig;
  }
  declare interface RecordAttachFunction {
    (options: AttachOptions): void;
    promise(options: AttachOptions): Promise<void>;
  }
  declare interface RecordCopyFunction {
    (options: CopyLoadOptions): Record;
    promise(options: CopyLoadOptions): Promise<Record>;
  }
  declare interface RecordCreateOptions {
    /**
     * The record type.
     */
    +type: $Values<TypeT> | string;

    /**
     * Determines whether the new record is dynamic. If set to true, the record is created in dynamic mode. If set to false, the record is created in standard mode. By default, this value is false.
     * - When a SuiteScript 2.0 script creates, copies, loads, or transforms a record in standard mode, the record’s body fields and sublist line items are not sourced, calculated, and validated until the record is saved (submitted) with Record.save(options).
     * - When you work with a record in standard mode, you do not need to set values in any particular order. After submitting the record, NetSuite processes the record’s body fields and sublist line items in the correct order, regardless of the organization of your script.
     * - When a SuiteScript 2.0 script creates, copies, loads, or transforms a record in dynamic mode, the record’s body fields and sublist line items are sourced, calculated, and validated in real-time. A record in dynamic mode emulates the behavior of a record in the UI.
     * - When you work with a record in dynamic mode, it is important that you set values in the same order you would within the UI. If you fail to do this, your results may not be accurate.
     */
    isDynamic?: boolean;

    /**
     * Name-value pairs containing default values of fields in the new record.
     */
    defaultValues?: any;
  }
  /**
   * Create a new record object based on provided type
   * @governance 10 units for transactions, 2 for custom records, 5 for all other records
   * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT if options.type is missing
   */
  declare interface RecordCreateFunction {
    (options: RecordCreateOptions): Record;
    promise(options: RecordCreateOptions): Promise<Record>;
  }
  declare interface RecordDeleteOptions {
    /**
     * The record type.
     */
    +type: $Values<TypeT> | string;

    /**
     * The internal ID of the record instance to be deleted.
     */
    +id: string | number;
  }
  declare interface RecordDetachFunction {
    (options: DetachOptions): void;
    promise(options: DetachOptions): Promise<void>;
  }
  /**
   * Loads an existing nlobjRecord from the database based on provided type, id
   * @governance 10 units for transactions, 2 for custom records, 5 for all other records
   * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT if options.type or options.id is missing
   */
  declare interface RecordLoadFunction {
    (options: CopyLoadOptions): Record;
    promise(options: CopyLoadOptions): Promise<Record>;
  }
  /**
   * Delete a record object based on provided type, id and return the id of deleted record
   * @governance 20 units for transactions, 4 for custom records, 10 for all other records
   * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT if type or id is missing
   * @since 2015.2
   */
  declare interface RecordDeleteFunction {
    (options: RecordDeleteOptions): void;
    promise(options: RecordDeleteOptions): Promise<void>;
  }
  /**
   * Transform a record into another type (i.e. salesOrder -> invoice -or- opportunity -> estimate)
   * @governance 10 units for transactions, 2 for custom records, 5 for all other records
   * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT if options.type or options.id is missing
   */
  declare interface RecordTransformFunction {
    (options: RecordTransformOptions): Record;
    promise(options: RecordTransformOptions): Promise<Record>;
  }
  declare interface RecordTransformOptions {
    /**
     * The record type of the existing record instance being transformed.
     */
    +fromType: string | $Values<TypeT>;

    /**
     * The internal ID of the existing record instance being transformed.
     */
    fromId: number;

    /**
     * The record type of the record returned when the transformation is complete.
     */
    +toType: string | $Values<TypeT>;

    /**
     * If set to true, the new record is created in dynamic mode. If set to false, the new record is created in standard mode.
     */
    isDynamic?: boolean;

    /**
     * Name-value pairs containing default values of fields in the new record.
     */
    defaultValues?: any;
  }

  declare type TypeT = {|
                        +ACCOUNT: 0, // 0
                        +ACCOUNTING_BOOK: 1, // 1
                        +ACCOUNTING_CONTEXT: 2, // 2
                        +ACCOUNTING_PERIOD: 3, // 3
                        +ADV_INTER_COMPANY_JOURNAL_ENTRY: 4, // 4
                        +ALLOCATION_SCHEDULE: 5, // 5
                        +AMORTIZATION_SCHEDULE: 6, // 6
                        +AMORTIZATION_TEMPLATE: 7, // 7
                        +ASSEMBLY_BUILD: 8, // 8
                        +ASSEMBLY_ITEM: 9, // 9
                        +ASSEMBLY_UNBUILD: 10, // 10
                        +BILLING_ACCOUNT: 11, // 11
                        +BILLING_CLASS: 12, // 12
                        +BILLING_RATE_CARD: 13, // 13
                        +BILLING_REVENUE_EVENT: 14, // 14
                        +BILLING_SCHEDULE: 15, // 15
                        +BIN: 16, // 16
                        +BIN_TRANSFER: 17, // 17
                        +BIN_WORKSHEET: 18, // 18
                        +BLANKET_PURCHASE_ORDER: 19, // 19
                        +BOM: 20, // 20
                        +BOM_REVISION: 21, // 21
                        +BULK_OWNERSHIP_TRANSFER: 22, // 22
                        +BUNDLE_INSTALLATION_SCRIPT: 23, // 23
                        +CALENDAR_EVENT: 24, // 24
                        +CAMPAIGN: 25, // 25
                        +CAMPAIGN_RESPONSE: 26, // 26
                        +CAMPAIGN_TEMPLATE: 27, // 27
                        +CASH_REFUND: 28, // 28
                        +CASH_SALE: 29, // 29
                        +CHARGE: 30, // 30
                        +CHARGE_RULE: 31, // 31
                        +CHECK: 32, // 32
                        +CLASSIFICATION: 33, // 33
                        +CLIENT_SCRIPT: 34, // 34
                        +CMS_CONTENT: 35, // 35
                        +CMS_CONTENT_TYPE: 36, // 36
                        +CMS_PAGE: 37, // 37
                        +COMMERCE_CATEGORY: 38, // 38
                        +COMPETITOR: 39, // 39
                        +CONSOLIDATED_EXCHANGE_RATE: 40, // 40
                        +CONTACT: 41, // 41
                        +CONTACT_CATEGORY: 42, // 42
                        +CONTACT_ROLE: 43, // 43
                        +COST_CATEGORY: 44, // 44
                        +COUPON_CODE: 45, // 45
                        +CREDIT_CARD_CHARGE: 46, // 46
                        +CREDIT_CARD_REFUND: 47, // 47
                        +CREDIT_MEMO: 48, // 48
                        +CURRENCY: 49, // 49
                        +CUSTOMER: 50, // 50
                        +CUSTOMER_CATEGORY: 51, // 51
                        +CUSTOMER_DEPOSIT: 52, // 52
                        +CUSTOMER_MESSAGE: 53, // 53
                        +CUSTOMER_PAYMENT: 54, // 54
                        +CUSTOMER_PAYMENT_AUTHORIZATION: 55, // 55
                        +CUSTOMER_REFUND: 56, // 56
                        +CUSTOMER_STATUS: 57, // 57
                        +CUSTOMER_SUBSIDIARY_RELATIONSHIP: 58, // 58
                        +CUSTOM_RECORD: 59, // 59
                        +CUSTOM_TRANSACTION: 60, // 60
                        +DEPARTMENT: 61, // 61
                        +DEPOSIT: 62, // 62
                        +DEPOSIT_APPLICATION: 63, // 63
                        +DESCRIPTION_ITEM: 64, // 64
                        +DISCOUNT_ITEM: 65, // 65
                        +DOWNLOAD_ITEM: 66, // 66
                        +DRIVERS_LICENSE: 67, // 67
                        +EMAIL_TEMPLATE: 68, // 68
                        +EMPLOYEE: 69, // 69
                        +ENTITY_ACCOUNT_MAPPING: 70, // 70
                        +ESTIMATE: 71, // 71
                        +EXPENSE_CATEGORY: 72, // 72
                        +EXPENSE_REPORT: 73, // 73
                        +FAIR_VALUE_PRICE: 74, // 74
                        +FIXED_AMOUNT_PROJECT_REVENUE_RULE: 75, // 75
                        +FOLDER: 76, // 76
                        +FULFILLMENT_REQUEST: 77, // 77
                        +GENERAL_TOKEN: 78, // 78
                        +GENERIC_RESOURCE: 79, // 79
                        +GIFT_CERTIFICATE: 80, // 80
                        +GIFT_CERTIFICATE_ITEM: 81, // 81
                        +GLOBAL_ACCOUNT_MAPPING: 82, // 82
                        +GLOBAL_INVENTORY_RELATIONSHIP: 83, // 83
                        +GOVERNMENT_ISSUED_ID_TYPE: 84, // 84
                        +HCM_JOB: 85, // 85
                        +INBOUND_SHIPMENT: 86, // 86
                        +INTERCOMP_ALLOCATION_SCHEDULE: 87, // 87
                        +INTER_COMPANY_JOURNAL_ENTRY: 88, // 88
                        +INTER_COMPANY_TRANSFER_ORDER: 89, // 89
                        +INVENTORY_ADJUSTMENT: 90, // 90
                        +INVENTORY_COST_REVALUATION: 91, // 91
                        +INVENTORY_COUNT: 92, // 92
                        +INVENTORY_DETAIL: 93, // 93
                        +INVENTORY_ITEM: 94, // 94
                        +INVENTORY_NUMBER: 95, // 95
                        +INVENTORY_STATUS: 96, // 96
                        +INVENTORY_STATUS_CHANGE: 97, // 97
                        +INVENTORY_TRANSFER: 98, // 98
                        +INVOICE: 99, // 99
                        +ISSUE: 100, // 100
                        +ISSUE_PRODUCT: 101, // 101
                        +ISSUE_PRODUCT_VERSION: 102, // 102
                        +ITEM_ACCOUNT_MAPPING: 103, // 103
                        +ITEM_DEMAND_PLAN: 104, // 104
                        +ITEM_FULFILLMENT: 105, // 105
                        +ITEM_GROUP: 106, // 106
                        +ITEM_LOCATION_CONFIGURATION: 107, // 107
                        +ITEM_RECEIPT: 108, // 108
                        +ITEM_REVISION: 109, // 109
                        +ITEM_SUPPLY_PLAN: 110, // 110
                        +JOB: 111, // 111
                        +JOB_REQUISITION: 112, // 112
                        +JOB_STATUS: 113, // 113
                        +JOB_TYPE: 114, // 114
                        +JOURNAL_ENTRY: 115, // 115
                        +KIT_ITEM: 116, // 116
                        +KUDOS: 117, // 117
                        +LABOR_BASED_PROJECT_REVENUE_RULE: 118, // 118
                        +LEAD: 119, // 119
                        +LOCATION: 120, // 120
                        +LOT_NUMBERED_ASSEMBLY_ITEM: 121, // 121
                        +LOT_NUMBERED_INVENTORY_ITEM: 122, // 122
                        +MANUFACTURING_COST_TEMPLATE: 123, // 123
                        +MANUFACTURING_OPERATION_TASK: 124, // 124
                        +MANUFACTURING_ROUTING: 125, // 125
                        +MAP_REDUCE_SCRIPT: 126, // 126
                        +MARKUP_ITEM: 127, // 127
                        +MASSUPDATE_SCRIPT: 128, // 128
                        +MERCHANDISE_HIERARCHY_LEVEL: 129, // 129
                        +MERCHANDISE_HIERARCHY_NODE: 130, // 130
                        +MERCHANDISE_HIERARCHY_VERSION: 131, // 131
                        +MESSAGE: 132, // 132
                        +MFG_PLANNED_TIME: 133, // 133
                        +NEXUS: 134, // 134
                        +NON_INVENTORY_ITEM: 135, // 135
                        +NOTE: 136, // 136
                        +NOTE_TYPE: 137, // 137
                        +OPPORTUNITY: 138, // 138
                        +ORDER_SCHEDULE: 139, // 139
                        +ORGANIZATION_VALUE: 140, // 140
                        +OTHER_CHARGE_ITEM: 141, // 141
                        +OTHER_GOVERNMENT_ISSUED_ID: 142, // 142
                        +OTHER_NAME: 143, // 143
                        +OTHER_NAME_CATEGORY: 144, // 144
                        +PARTNER: 145, // 145
                        +PARTNER_CATEGORY: 146, // 146
                        +PASSPORT: 147, // 147
                        +PAYCHECK: 148, // 148
                        +PAYCHECK_JOURNAL: 149, // 149
                        +PAYMENT_CARD: 150, // 150
                        +PAYMENT_CARD_TOKEN: 151, // 151
                        +PAYMENT_ITEM: 152, // 152
                        +PAYMENT_METHOD: 153, // 153
                        +PAYROLL_ITEM: 154, // 154
                        +PERIOD_END_JOURNAL: 155, // 155
                        +PCT_COMPLETE_PROJECT_REVENUE_RULE: 156, // 156
                        +PHONE_CALL: 157, // 157
                        +PORTLET: 158, // 158
                        +POSITION: 159, // 159
                        +PRICE_BOOK: 160, // 160
                        +PRICE_LEVEL: 161, // 161
                        +PRICE_PLAN: 162, // 162
                        +PRICING_GROUP: 163, // 163
                        +PROJECT_EXPENSE_TYPE: 164, // 164
                        +PROJECT_TASK: 165, // 165
                        +PROJECT_TEMPLATE: 166, // 166
                        +PROMOTION_CODE: 167, // 167
                        +PROSPECT: 168, // 168
                        +PURCHASE_CONTRACT: 169, // 169
                        +PURCHASE_ORDER: 170, // 170
                        +PURCHASE_REQUISITION: 171, // 171
                        +RATE_PLAN: 172, // 172
                        +REALLOCATE_ITEM: 173, // 173
                        +RECEIVE_INBOUND_SHIPMENT: 174, // 174
                        +RESOURCE_ALLOCATION: 175, // 175
                        +RESTLET: 176, // 176
                        +RETURN_AUTHORIZATION: 177, // 177
                        +REVENUE_ARRANGEMENT: 178, // 178
                        +REVENUE_COMMITMENT: 179, // 179
                        +REVENUE_COMMITMENT_REVERSAL: 180, // 180
                        +REVENUE_PLAN: 181, // 181
                        +REV_REC_SCHEDULE: 182, // 182
                        +REV_REC_TEMPLATE: 183, // 183
                        +SALES_ORDER: 184, // 184
                        +SALES_ROLE: 185, // 185
                        +SALES_TAX_ITEM: 186, // 186
                        +SCHEDULED_SCRIPT: 187, // 187
                        +SCHEDULED_SCRIPT_INSTANCE: 188, // 188
                        +SCRIPT_DEPLOYMENT: 189, // 189
                        +SERIALIZED_ASSEMBLY_ITEM: 190, // 190
                        +SERIALIZED_INVENTORY_ITEM: 191, // 191
                        +SERVICE_ITEM: 192, // 192
                        +SHIP_ITEM: 193, // 193
                        +SOLUTION: 194, // 194
                        +STATISTICAL_JOURNAL_ENTRY: 195, // 195
                        +STORE_PICKUP_FULFILLMENT: 196, // 196
                        +SUBSCRIPTION: 197, // 197
                        +SUBSCRIPTION_CHANGE_ORDER: 198, // 198
                        +SUBSCRIPTION_LINE: 199, // 199
                        +SUBSCRIPTION_PLAN: 200, // 200
                        +SUBSIDIARY: 201, // 201
                        +SUBTOTAL_ITEM: 202, // 202
                        +SUITELET: 203, // 203
                        +SUPPLY_CHAIN_SNAPSHOT: 204, // 204
                        +SUPPORT_CASE: 205, // 205
                        +TASK: 206, // 206
                        +TAX_ACCT: 207, // 207
                        +TAX_GROUP: 208, // 208
                        +TAX_PERIOD: 209, // 209
                        +TAX_TYPE: 210, // 210
                        +TERM: 211, // 211
                        +TERMINATION_REASON: 212, // 212
                        +TIME_BILL: 213, // 213
                        +TIME_ENTRY: 214, // 214
                        +TIME_OFF_CHANGE: 215, // 215
                        +TIME_OFF_PLAN: 216, // 216
                        +TIME_OFF_REQUEST: 217, // 217
                        +TIME_OFF_RULE: 218, // 218
                        +TIME_OFF_TYPE: 219, // 219
                        +TIME_SHEET: 220, // 220
                        +TOPIC: 221, // 221
                        +TRANSFER_ORDER: 222, // 222
                        +UNITS_TYPE: 223, // 223
                        +USAGE: 224, // 224
                        +USEREVENT_SCRIPT: 225, // 225
                        +VENDOR: 226, // 226
                        +VENDOR_BILL: 227, // 227
                        +VENDOR_CATEGORY: 228, // 228
                        +VENDOR_CREDIT: 229, // 229
                        +VENDOR_PAYMENT: 230, // 230
                        +VENDOR_RETURN_AUTHORIZATION: 231, // 231
                        +VENDOR_SUBSIDIARY_RELATIONSHIP: 232, // 232
                        +WEBSITE: 233, // 233
                        +WORKFLOW_ACTION_SCRIPT: 234, // 234
                        +WORK_ORDER: 235, // 235
                        +WORK_ORDER_CLOSE: 236, // 236
                        +WORK_ORDER_COMPLETION: 237, // 237
                        +WORK_ORDER_ISSUE: 238, // 238
                        +WORKPLACE: 239 // 239
                        |};

  declare export interface NRecord {
    /**
     * Attaches a record to another record.
     */
    attach: RecordAttachFunction;
    /**
     * Creates a new record by copying an existing record in NetSuite.
     */
    copy: RecordCopyFunction;
    /**
     * Creates a new record.
     */
    create: RecordCreateFunction;
    /**
     * Deletes a record.
     */
    delete: RecordDeleteFunction;

    /**
     * Detaches a record from another record.
     */
    detach: RecordDetachFunction;
    /**
     * Loads an existing nlobjRecord from the database based on provided type, id
     * @governance 10 units for transactions, 2 for custom records, 5 for all other records
     * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT if options.type or options.id is missing
     */
    load: RecordLoadFunction;
    /**
     * commit record field updates to the system.
     *
     * Updates and submits one or more body fields on an existing record in NetSuite, and returns the internal ID of the parent record.
     * When you use this method, you do not need to load or submit the parent record.
     * You can use this method to edit and submit the following:
     * - Standard body fields that support inline editing (direct list editing). For more information, see Using Inline Editing.
     * - Custom body fields that support inline editing.
     * You cannot use this method to edit and submit the following:
     * - Select fields
     * - Sublist line item fields
     * - Subrecord fields (for example, address fields)
     *
     * The 'value' parameter in this function is an object with matching properties and values.
     * ex.: value: {'name': 'Bob', 'department': '12'}
     *
     * @governance 10 units for transactions, 2 for custom records, 5 for all other records
     * @restriction only supported for records and fields where DLE (Direct List Editing) is supported
     * @return {number} id of submitted record
     * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT if type or id is missing
     */
    submitFields: {
      (options: SubmitFieldsOptions): number;
      promise(options: SubmitFieldsOptions): Promise<number>;
    };
    /**
     * Transforms a record from one type into another, using data from an existing record.
     */
    transform: RecordTransformFunction;
    /**
     * N/record.Type enum
     */
    Type: TypeT;
  }

}
