/**
 * Flowtype definitions for sso
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.10.0
 */

declare module 'N/sso' {

  declare interface GenerateSuiteSignOnTokenOptions {
    suiteSignOnId: string;
  }

  declare export interface NSso {
    generateSuiteSignOnToken(options: GenerateSuiteSignOnTokenOptions): string;
  }

}
