/**
 * Flowtype definitions for transaction
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.10.0
 * @flow
 */

declare module 'N/transaction' {

  declare interface VoidOptions {
      +id: number | string;
    type: string;
  }
  declare interface TransactionVoidFunction {
    (options: VoidOptions): number;
    promise(options: VoidOptions): Promise<number>;
  }

  declare export interface NTransaction {
    void: TransactionVoidFunction;
  }

}
