/**
 * Flowtype definitions for url
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.10.0
 */

declare module 'N/url' {

  declare interface formatOptions {
    domain: string;
    params: any;
  }
  declare interface resolveHostOptions {
    /**
     * The type of domain name you want to retrieve. Set this value using the url.HostType enum.
     */
    hostType: $Values<typeof HostType>;

    /**
     * The NetSuite account ID for which you want to retrieve data. If no account is specified, the system returns data on the account that is running the script.
     */
    accountId?: string;
  }
  declare interface resolveRecordOptions {
    recordType: string;
    +recordId: string | number;
    isEditMode?: boolean;
    params?: any;
  }
  declare interface resolveScriptOptions {
    scriptId: string;
    deploymentId: string;
    returnExternalUrl?: boolean;
    params?: any;
  }
  declare interface resolveTaskLinkOptions {
    id: string;
    params?: any;
  }

  declare type HostTypeT = {|
                            +APPLICATION: 0, // 0
                            +CUSTOMER_CENTER: 1, // 1
                            +FORM: 2, // 2
                            +RESTLET: 3, // 3
                            +SUITETALK: 4 // 4
                            |};

  declare export interface NUrl {
    /**
     * Creates a serialized representation of an object containing query parameters. Use the returned value to build a URL query string.
     */
    format(options: formatOptions): string;

    /**
     * Returns a domain name for a NetSuite account.
     */
    resolveDomain(options: resolveHostOptions): string;

    /**
     * Returns the URL string to a NetSuite record.
     */
    resolveRecord(options: resolveRecordOptions): string;

    /**
     * Returns an external or internal URL string to a script.
     */
    resolveScript(options: resolveScriptOptions): string;

    /**
     * Returns the internal URL to a NetSuite tasklink.
     */
    resolveTaskLink(
      options: resolveTaskLinkOptions
    ): string;

    HostType: HostTypeT;
  }

}
